### ISSUE TITLE
Error while setting the Trees! SimulationIndex 1 is not valid.

### ISSUE THREAD

**Issue by mlcraig** [Open-Systems-Pharmacology/Matlab-Toolbox#32] opened 2017-06-23 14:56 UTC
I wasn't sure of the procedure (I'm new to github) so I've started a new issue for the latest warning error I get when I'm trying to load an .xml project file from PK Sim/MoBi in Matlab (this is the same issue as my last post in issue #31 ). I have added the code and auxiliary folders to the path using pathtool. If I select any file in the GUI (including the examples provided during installation of the OSP suite), I now have the following error:

"Error while setting the Trees! SimulationIndex 1 is not valid. There is none simulation initialized."

Any ideas? I've gone into the generateMatlabCodeForXML.m file and located the line giving the error but I'm not sure how to fix it.

**Comment by msevestre** [comment] 2017-06-23 15:20
What about https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox/issues/30
Can you select a file where you have write access and let us know if this fixes the issue?

**Comment by msevestre** [comment] 2017-06-23 15:22
@mlcraig Yes this is absolutely the preferred procedure. One entry per problem otherwise we very quickly lose the overview of what's going on :)

**Comment by mlcraig** [comment] 2017-06-23 17:19
@msevestre I tried both with example files in the code folders and my own generated .xml files in my own user folder so I have write access on the latter. The source of the warning seems to be from lines 516-519 in generateMatlabCodeForXML.m, but I haven't gone into great detail to chase it down:

 `catch exception 
        set(handles.OK_pushbutton,'Enable','off');
        set(handles.warning_text,'String',['Error while setting the Trees!' char(10) exception.message]);
    end`

**Comment by msevestre** [comment] 2017-06-23 17:22
@mlcraig Just to make sure: You still get this error even if you are using a folder where you have write access?

**Comment by mlcraig** [comment] 2017-06-23 17:24
@msevestre Correct, I get it on both the examples in the program files and in my own files saved to a folder in my user directory.

**Comment by msevestre** [comment] 2017-06-23 17:24
@KatrinCoboeken  @PavelBal, @TheiBa: Do you have any more suggestion as to a work around until the issue is fixed?

**Comment by mlcraig** [comment] 2017-06-26 14:56
Hi @msevestre just wondering if you had any further ideas as I am still unable to manipulate any exported file in Matlab?

**Comment by msevestre** [comment] 2017-06-26 14:58
@mlcraig no sorry.  I am waiting for one of our Matlab Toolbox guru to chime in :)

**Comment by KatrinCoboeken** [comment] 2017-06-26 15:39
@mlcraig I assume the initialization failed. This can have several reasons. The easiest to solve would be, that you still do not have all paths. The folder code has to be added, with all subfolders and the folder lib has to be added.
If this does not help. Could you call the function initSimulation directly and send me the error message? 
Just call initSimulation('examples\models\PopSim.xml',[]), with the modelpath adjusted to your model.

**Comment by mlcraig** [comment] 2017-06-26 15:55
Hi @KatrinCoboeken thank you so much! I can now load the xml file, you are correct that I had a problem with the paths. Using pathtool again, I removed the previously added folders and re-added the code folder (with its subfolders) and the lib folder. Now the model loads when I run the generateMatlabCodeForXML GUI.

The following warning appeared however when running the GUI: "Warning: Name is nonexistent or not a directory: C:\Users\name\AppData\Roaming\Open Systems Pharmacology\MobiToolboxForMatlab", have I missed something in the path?

**Comment by msevestre** [comment] 2017-06-26 18:11
@mlcraig 
`C:\Users\name\AppData\Roaming\Open Systems Pharmacology\MobiToolboxForMatlab`

Is your userId `name` ?? I suspect not . Where is this path coming from?
Did you set it up somewhere?

**Comment by mlcraig** [comment] 2017-06-26 18:45
@msevestre I'm sorry, I should have said that 'name' is the user name of the folder. 

The path as written (substituting my user name for 'name') was in the warning in the command window after running the gui to load the .xml project file after resetting the paths as suggested by KatrinCoboeken. The initialisation ran without issue however (it was a Matlab warning not an error). Hope that helps?

**Comment by msevestre** [comment] 2017-06-26 19:12
@mlcraig If I understand you correctly, the warning is
Warning: `<USER_NAME>` is nonexistent or not a directory: C:\Users\<USER_NAME>\AppData\Roaming\Open Systems Pharmacology\MobiToolboxForMatlab"

and `<USER_NAME>` is actually your windows user that was replaced in the Github issue only? Confusing :)

@KatrinCoboeken  Is anything being loaded from the local user folder? The setup does not install anything here as far as I can tell

**Comment by KatrinCoboeken** [comment] 2017-06-27 06:36
Yes, Matlab saves the list of available units and dimension (lib/OPSuiteDimension.xml) in a .mat file and saves it in this local folder. This saves some time, as the xml parser is not needed any more, and additionally the user can add project specific units.
The directory is created automatically during model initialization. @mlcraig, you should now have this path, containing a unitList_0.mat, and the warning should no occur anymore.
@msevestre I will change the order of calls, first folder creation and then adding to the path, so that the warning will not appear anymore.

**Comment by msevestre** [comment] 2017-06-27 14:24
Ok let's close this issue then. I'll create a new one for the request
@KatrinCoboeken Let's make sure that the dimension file is saved in a folder containing the version number as well
typically
`C:\Users\<USER_NAME>\AppData\Roaming\Open Systems Pharmacology\MobiToolboxForMatlab\7.2`

(e.g. the version number at the end)

**Closed as completed** 2017-06-27 14:28 UTC
